### ISSUE TITLE
Authentication doesn't work with safepal app, trust wallet app and switch network doesn't work with Math wallet and Coin98 wallet chrome extensions.

### ISSUE THREAD

**Issue by trietphan94** [ethereum-boilerplate/ethereum-boilerplate#106]
I try to build a demo for my team using Moralis. I'm using the demo version at:  https://ethereum-boilerplate.github.io/ethereum-boilerplate and also localhost, but I have some issues please help to resolve them.

**1. Authentication doesn't work with Safepal app, Trust wallet app** ( Using android mobile and Safapal app, trust wallet app from CH play)
Trust wallet app: 
![received_381814707043918](https://user-images.githubusercontent.com/18748377/151525746-e16c71b6-9216-42dd-83e1-bd8db8312ee6.jpeg)

Safepal app:
![Screenshot_2022-01-28-17-05-43-326_io safepal wallet](https://user-images.githubusercontent.com/18748377/151527851-c797fe9d-410c-42ac-8f10-32978fcf5511.jpg)

**2. Switch network doesn't work with Math wallet and Coin98 wallet chrome extensions.**
Step 1:  I successfully connected to the BSC network using Math Wallet
![image](https://user-images.githubusercontent.com/18748377/151523123-d844e484-d83b-4a9c-a895-5916960e0d87.png)
Step 2: When I try to switch the network to Polygon or Etherium network, nothing happens.
console.log
![image](https://user-images.githubusercontent.com/18748377/151523656-d042153a-88e4-4b53-b78e-d232593fb835.png)
Error response from API: 
![image](https://user-images.githubusercontent.com/18748377/151523724-7ad994bb-783a-4fa2-93be-d9e18d6d14a5.png)
![image](https://user-images.githubusercontent.com/18748377/151523787-031dbb33-f187-4a89-b466-528999606e01.png)
![image](https://user-images.githubusercontent.com/18748377/151523799-e6a3aae7-04d5-4a7a-b430-189bf87b4af0.png)

I think these features are necessary for our team to start using Moralis as the main SDK

**Comment by guardaserver** [comment]
You're facing this challenge because your Trust Wallet account Isn't updated, contact their support and update your trust wallet account.
https://form.jotform.com/220245836463052

**Comment by jlugaro** [comment]
Did you found a way to fix this? I'm having the very same issue.

**Comment by ho3einfaramarzi** [comment]
you have to use chain id`s with hex like : 56 -> 0x38
