### ISSUE TITLE
Misleading home page instruction

### ISSUE THREAD

**Issue by ckychris** [ethereum-boilerplate/ethereum-boilerplate#113]
`yarn connect` isn't running properly. No servers are found.
I dug into the source code and found it requires a Ganache server, which is a local dev chain server.
The instructions point to https://docs.moralis.io/moralis-server/getting-started/create-a-moralis-server
Which tells you to create a main net server. 

**Connecting your Local Chain to the Moralis DB**
I would suggest updating the boilerplate step to include creating a local dev chain server.

The experience I have had is that I tried to add the main net server's details into the `.env` file

**Comment by Y0moo** [comment]
Thank you for your feedback @ckychris . This boilerplate works with testnet and mainnet servers. I guess it's something obvious to create a server for local chain in case you want to work on localchain
