### ISSUE TITLE
can't interact with ui on windows 11. MacOS is fine.

### ISSUE THREAD

**Issue by Ozdemir-B** [ethereum-boilerplate/ethereum-boilerplate#116]
I can't  click any button at all. Quickstart page opens default and stays at that page forever:) Any help?

**Comment by captvicky** [comment]
yes, me too, can't click button just star on quick start

**Comment by guymcmanusgithub** [comment]
I ran into this problem today.  To fix it go to the .eslintrc file, and update the "rules" part to look like this: 
`"rules": {
    "react/react-in-jsx-scope": "off",
    "react/prop-types": "off",
    "react/jsx-key": "off",
    "react/no-unescaped-entities": "off",
    "prettier/prettier": ["off", { "singleQuote": true }]
  }`

just add that last line that begins "prettier ...

**Comment by Y0moo** [comment]
This issue is related to different endings of code line on different OS. LF/CRLF. 

You can disable this rule by adding to the .eslint: 
```
'linebreak-style': 0,
```

**Comment by Metaartz** [comment]
> @captvicky Have you tried `yarn format`?

You should include this in the install instructions.
