### ISSUE TITLE
Only Binance Smart Chain Balance is loading 

### ISSUE THREAD

**Issue by CryptoR2022** [ethereum-boilerplate/ethereum-boilerplate#118]
ETHEREUM, Avalanche, Polygon balances are not loading and also NFT integration is failing

**Comment by danju4rizzl** [comment]
I get the balances for all the networks but not so sure about NFT... What errors are you getting?

**Comment by YosephKS** [comment]
@CryptoR2022 hey what do you exactly mean by failing?
