### ISSUE TITLE
Swap Custom Token

### ISSUE THREAD

**Issue by 2kenyo** [ethereum-boilerplate/ethereum-boilerplate#123]
I have custom token on BSC Network, when I try add my Custom token to token list is OK after when I wanna do swap they can not calculate liquidity, 

(Custom token have liquidity on Pancakeswap but here is supported only liquidity from 1inch plugin)

I sent message to 1inch support and they say that Moralis 1inch plugin is out of date.

I only want to be sure if I have liquidity on 1inch does Moralis 1inch plugin **OUTDATED** support new custom tokens.

**Comment by CryptoLover705** [comment]
Simply add liquidity to 1inch and it will resolve your issue

**Comment by Y0moo** [comment]
Closing since we released V2
