### ISSUE TITLE
Wallet Transfer - Button not updating status

### ISSUE THREAD

**Issue by beyondthecode-bc** [ethereum-boilerplate/ethereum-boilerplate#125]
**const txStatus = await Moralis.transfer(options); is not returned as a function.**

Hence, the below error is thrown:
https://moralis-forum.s3.dualstack.eu-north-1.amazonaws.com/original/2X/b/b0163cfa8c3ad964ef62dd16fd30f4d3d52f0e36.png

` setIsPending(true);
    const txStatus = await Moralis.transfer(options);
    console.log(txStatus)

    txStatus
      .on("transactionHash", (hash) => {
        openNotification({
          message: "🔊 New Transaction",
          description: `${hash}`,
        });
        console.log("🔊 New Transaction", hash);
      })
      .on("receipt", (receipt) => {
        openNotification({
          message: "📃 New Receipt",
          description: `${receipt.transactionHash}`,
        });
        console.log("🔊 New Receipt: ", receipt);
        setIsPending(false);
      })
      .on("error", (error) => {
        openNotification({
          message: "📃 Error",
          description: `${error.message}`,
        });
        console.error(error);
        setIsPending(false);
      });
  }`

Result of the console.log event:

https://moralis-forum.s3.dualstack.eu-north-1.amazonaws.com/original/2X/8/87391f73048d6b64af4925d141e0fa724bb7a2b5.png

Moralis - 1.3.2
React-Moralis - 1.3.1
Server Version - 0.0.347

**Comment by beyondthecode-bc** [comment]
Same issue with the latest Moralis version:

Moralis - 1.3.5
React-Moralis - 1.3.2
Server Version - 0.0.353

```
Uncaught (in promise) TypeError: txStatus.on is not a function
    at transfer (static/js/main.chunk.js:7150:14)
```

**Comment by Y0moo** [comment]
Closing since we released V2
