### ISSUE TITLE
Chains not updating when switching chains.

### ISSUE THREAD

**Issue by daniel-makarov** [ethereum-boilerplate/ethereum-boilerplate#129]
Whenever I try to switch chains, the logo and title of the chain that I am connecting to disappear. It only reappears when I refresh the site. This was never a problem on older versions of the site.

Below is a video showcasing the problem.

I did not tamper with the code in any way, just cloned it from the Github.

https://user-images.githubusercontent.com/73257550/155864232-274d463e-ed6c-4df9-bfbd-41230edd7a4c.mov

.

**Comment by Y0moo** [comment]
Hi @daniel-makarov 

Could you share the console?

**Comment by daniel-makarov** [comment]
> 

Sure! Here is a video of it!

**Comment by daniel-makarov** [comment]
> 

I think i accidentally closed the issue. :( My bad. The problem is still here

**Comment by haggisswap** [comment]
Hi @daniel-makarov just bringing this back to your attention as this seems to be happening to a lot of people. See discussion here: https://discord.com/channels/819584798443569182/922873005170917416

**Comment by mubarakone** [comment]
https://github.com/ethereum-boilerplate/ethereum-boilerplate/pull/147#issue-1207796046
Here's a temporary fix, however the page needs to be refreshed to re-render the page.

**Comment by Y0moo** [comment]
Closing since we released V2
