### ISSUE TITLE
Page unresponsive after cloning and running yarn install

### ISSUE THREAD

**Issue by janvinsha** [ethereum-boilerplate/ethereum-boilerplate#130]
This problem is caused by the react-scripts version, quick fix is adding this `  "resolutions": {
    "react-error-overlay": "6.0.9"
  }` to the package.json and running yarn install again
Note: all errors/warnings need to be fixed when using this resolution or the app won't run

**Comment by janvinsha** [comment]
To avoid errors from prettier, run yarn format before starting the application

**Comment by Y0moo** [comment]
Closing since we released V2
