### ISSUE TITLE
Wallet WSOD after CHAIN switch!!!

### ISSUE THREAD

**Issue by thaylongdeptrai** [ethereum-boilerplate/ethereum-boilerplate#133]
I have followed all the instructions on setting up the ethereum-boilerplate.

Here are the steps to reproduce the error...

### 1. The quick start page
![image](https://user-images.githubusercontent.com/101083731/156986796-52bb697b-75c3-45a9-8d24-a20f8555dd77.png)

### 2. Authenticate with MetaMask wallet.
![image](https://user-images.githubusercontent.com/101083731/156986959-1461da1e-6baf-419e-9cb1-acc9da70e2fe.png)
![image](https://user-images.githubusercontent.com/101083731/156987011-a2b94229-66d7-4027-a0d7-48231c748775.png)
![image](https://user-images.githubusercontent.com/101083731/156987050-6df184dd-0d9f-4ead-8a91-fa8cd266378d.png)

### 3. Navigate to Wallet NavLink (Works!)
![image](https://user-images.githubusercontent.com/101083731/156987166-e73529ad-54b6-4524-8cc2-6e846b7a5751.png)

### 4. Change from Polygon Network to Ethereum
![image](https://user-images.githubusercontent.com/101083731/156987489-923161f4-b95c-49bf-822a-0e6704a62667.png)

I'm at a loss.......

**Comment by mubarakone** [comment]
https://github.com/ethereum-boilerplate/ethereum-boilerplate/pull/147#issue-1207796046
You are gonna have to refresh the page after switching networks however

**Comment by Y0moo** [comment]
Closing since we released V2
