### ISSUE TITLE
ERROR: no-unsafe-optional-chaining

### ISSUE THREAD

**Issue by themousery** [ethereum-boilerplate/ethereum-boilerplate#135]
I followed the setup instructions exactly but I get the error:

```
ERROR in src/components/Contract/Contract.jsx
  Line 90:34:  Unsafe usage of optional chaining. If it short-circuits with 'undefined' the evaluation will throw TypeError  no-unsafe-optional-chaining
```
I also get 99 warnings about URLs that look like:

```
WARNING in ./node_modules/antd/dist/antd.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./node_modules/antd/dist/antd.css)
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map: 'webpack://antd/./components/time-picker/style/index.less' URL is not supported
 @ ./node_modules/antd/dist/antd.css 8:6-231 22:17-24 26:7-21 58:25-39 59:36-47 59:50-64 63:6-73:7 64:54-65 64:68-82 70:42-53 70:56-70 72:21-28 83:0-201 83:0-201 84:22-29 84:33-47 84:50-64 61:4-74:5
 @ ./src/App.jsx 18:0-28
 @ ./src/index.js 6:0-24 24:35-38
```

I have uninstalled and reinstalled yarn, and deleted and redid the ethereum-boilerplate setup. No matter what, I get 99 warnings and this error. I am on Manjaro Linux.

**Comment by codeReadyy** [comment]
Facing the same issue.. any luck?

**Comment by irpheus** [comment]
Also facing this very same issue. Ubuntu 20.04 LTS

**Comment by themousery** [comment]
The errors magically stopped, but it was all pretty buggy and would randomly crash. 

I ended up just building my own thing from scratch. It was faster than trying to get this working

**Comment by wjy8888840** [comment]
Change
`for (let method of contract?.abi ) `
to
`for (let method of contract?.abi ?? method) `

It works for me. 
macOS Monterey

**Comment by Nexidian** [comment]
Thank you @wjy8888840 for the workaround.

I've raised a PR to resolve this #139

**Comment by yash0903** [comment]
> Facing the same issue.. any luck @themousery?

which file it is in?

**Comment by Nexidian** [comment]
@yash0903 Please refer to my comments and my PR 

https://github.com/ethereum-boilerplate/ethereum-boilerplate/pull/139

**Comment by Nagacash** [comment]
I'm having issues with deploying my dapp , any idea what I'm doing wrong ?

<img width="459" alt="deploy" src="https://user-images.githubusercontent.com/79047179/166715144-bfbe72b4-863a-4f67-8286-b784eb9cbdf4.png">
<img width="240" alt="deploy2" src="https://user-images.githubusercontent.com/79047179/166715174-c1f400a5-a0f2-488a-8038-d61e780b6ff9.png">

**Comment by Belial-public** [comment]
#149 is cleaner

**Comment by anantsoftcomputin** [comment]
yarn global add typescript@latest use this command to update your typescript version. It worked for me.

**Comment by codecoronado** [comment]
> yarn global add typescript@latest use this command to update your typescript version. It worked for me.

Thank you. This command worked for me.

**Comment by Nagacash** [comment]
Thx a lot I got it working :)

**Comment by plexor** [comment]
Same issue 

> Change `for (let method of contract?.abi ) ` to `for (let method of contract?.abi ?? method) `
> 
> It works for me. macOS Monterey

This worked for me as well, thank you.

**Comment by tommyboy326** [comment]
> ?? method

Thanks you. It worked for me too. macOS M1

**Comment by Y0moo** [comment]
Closing since we released V2

**Comment by oojoseph67** [comment]
@Y0moo is V2 out yet cause I can't seem to find it
