### ISSUE TITLE
No Instructions for Running on an AWS/Azure Instance

### ISSUE THREAD

**Issue by jbb-kryo** [ethereum-boilerplate/ethereum-boilerplate#142]
Would be interested in running this script on an AWS or Azure instance, however no recommendations or instructions are provided. Is it even possible? Basically, how do I run this on a live webserver with a domain attached?

**Comment by Nexidian** [comment]
@jbb-kryo Good morning, 

Providing instructions for production ready versions on AWS is out of scope for this project. 

However to briefly answer your questions: 

- This project can run within AWS quite easily. As at its core this is a react application, you can have a look at setting yourself up on AWS Amplify  https://aws.amazon.com/getting-started/hands-on/build-react-app-amplify-graphql/module-one/?e=gs2020&p=build-a-react-app-intro

- As for attaching a domain have a look at the following documentation https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html
