### ISSUE TITLE
Can't get NFT Balance to show up.

### ISSUE THREAD

**Issue by PampMargera** [ethereum-boilerplate/ethereum-boilerplate#151]
I've scoured this the internet for any solution and all I found was an empty/deleted thread about.

I'm on BSC, I can see the wallet, Dex, transfers, and everything else except I can't get the NFT Balance to load. It just stay blank with everything I have tried. Literally everything else seems to work great except this one piece.

Has anyone else ran into this and found a solution? Any ideas what the problem could be?

**Comment by Rana-usman-ul-haq** [comment]
go to src>components>Menuitems.jsx and delete and edit menu items from there
