### ISSUE TITLE
react-app-rewired not found

### ISSUE THREAD

**Issue by sitanshu05** [ethereum-boilerplate/ethereum-boilerplate#155]
When I run yarn start I'm getting  an error saying react-app-rewired not found 
![image](https://user-images.githubusercontent.com/83655509/170450487-a9ab5475-7a98-42fd-8a83-3eceed619d8b.png)

**Comment by alexnguyennz** [comment]
Have you installed all the project dependencies with `yarn install`?

**Comment by Y0moo** [comment]
Closing since we released V2
