### ISSUE TITLE
When Compiling, receiving prettier/prettier error 

### ISSUE THREAD

**Issue by ADZYYYY** [ethereum-boilerplate/ethereum-boilerplate#156]
My program compiles fully when running npm start, however when running npm run build to create a production build,

I'm receiving the following error, this is straight from a git clone, only change to code is the .env file name and moralis url and app id

I tried deleting to file to debug and it just replaces the same error with other files.

Please help where possible.

PC MINGW64 ~/ethereum-boilerplate (main)
$ npm run build

> ethereum-boilerplate@0.1.0 build
> react-app-rewired build

Creating an optimized production build...
Failed to compile.

src\service-worker.js
  Line 1:43:    Delete `␍`  prettier/prettier
  Line 2:1:     Delete `␍`  prettier/prettier
  Line 3:42:    Delete `␍`  prettier/prettier
  Line 4:63:    Delete `␍`  prettier/prettier
  Line 5:63:    Delete `␍`  prettier/prettier
  Line 6:20:    Delete `␍`  prettier/prettier
  Line 7:62:    Delete `␍`  prettier/prettier
  Line 8:63:    Delete `␍`  prettier/prettier
  Line 9:1:     Delete `␍`  prettier/prettier
  Line 10:45:   Delete `␍`  prettier/prettier
  Line 11:55:   Delete `␍`  prettier/prettier
  Line 12:80:   Delete `␍`  prettier/prettier
  Line 13:49:   Delete `␍`  prettier/prettier
  Line 14:59:   Delete `␍`  prettier/prettier
  Line 15:1:    Delete `␍`  prettier/prettier
  Line 16:16:   Delete `␍`  prettier/prettier
  Line 17:1:    Delete `␍`  prettier/prettier
  Line 18:63:   Delete `␍`  prettier/prettier
  Line 19:61:   Delete `␍`  prettier/prettier
  Line 20:72:   Delete `␍`  prettier/prettier
  Line 21:70:   Delete `␍`  prettier/prettier
  Line 22:38:   Delete `␍`  prettier/prettier
  Line 23:1:    Delete `␍`  prettier/prettier
  Line 24:67:   Delete `␍`  prettier/prettier
  Line 25:59:   Delete `␍`  prettier/prettier
  Line 26:73:   Delete `␍`  prettier/prettier
  Line 27:60:   Delete `␍`  prettier/prettier
  Line 28:15:   Delete `␍`  prettier/prettier
  Line 29:73:   Delete `␍`  prettier/prettier
  Line 30:26:   Delete `␍`  prettier/prettier
  Line 31:41:   Delete `␍`  prettier/prettier
  Line 32:39:   Delete `␍`  prettier/prettier
  Line 33:20:   Delete `␍`  prettier/prettier
  Line 34:53:   Delete `␍`  prettier/prettier
  Line 35:1:    Delete `␍`  prettier/prettier
  Line 36:41:   Delete `␍`  prettier/prettier
  Line 37:20:   Delete `␍`  prettier/prettier
etc etc etc etc

**Comment by alexnguyennz** [comment]
You can add `"endOfLine": "auto"` to your project's .prettierrc file. That should get rid of these.

**Comment by alexnguyennz** [comment]
Try running the command `npm run format` or `yarn format`.

**Comment by fonko** [comment]
"endOfLine": "auto" worked for me, thanks!

**Comment by Y0moo** [comment]
Closing since we released V2
