### ISSUE TITLE
Error In Build 

### ISSUE THREAD

**Issue by mehulk13899** [ethereum-boilerplate/ethereum-boilerplate#157]
When We Run Build Command We will get new Error
<img width="1065" alt="Screenshot 2022-06-06 at 1 28 43 AM" src="https://user-images.githubusercontent.com/64455632/172068295-3d1a7560-806d-4ef9-ae25-7b433b3de6a6.png">
<img width="1111" alt="Screenshot 2022-06-06 at 1 29 04 AM" src="https://user-images.githubusercontent.com/64455632/172068306-8a1d8854-0a37-40cc-b58e-7cf2db90dbf3.png">
.

**Comment by Y0moo** [comment]
Closing since we released V2
