### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by nassersaazi** [ethereum-boilerplate/ethereum-boilerplate#16]
just a suggestion that we have a dedicated CONTRIBUTING.md page in the repo to succinctly guide people who would like to contribute to the project.

**Comment by sillybbbbb** [comment]
yeah, I want to join

**Comment by Y0moo** [comment]
Thank you! We will add it soon

**Comment by Y0moo** [comment]
Hi! We added CONTRIBUTING.md.

Could you suggest to us what info do we need to add there? 
Thank you!

https://github.com/ethereum-boilerplate/ethereum-boilerplate/blob/main/CONTRIBUTING.md
