### ISSUE TITLE
Integrating with tailwindcss

### ISSUE THREAD

**Issue by BUDDGUN92** [ethereum-boilerplate/ethereum-boilerplate#172]
1. Installed and configured tailwindcss, postcss and autoprefixer.
2. Removed craco and craco-less.
**But tailwindcss is not working.**

So, created a new react app,
1. Configured tailwindcss.
2. Added the components, hooks and helpers.
**Now the code isn't rendering**

ex:- 
`const { web3 } = useMoralis();` throws an error

**Comment by Y0moo** [comment]
Closing since we released V2
