### ISSUE TITLE
Error 500 on Connect Wallet running on localhost

### ISSUE THREAD

**Issue by niomartinez** [ethereum-boilerplate/ethereum-boilerplate#177]
Following the documentation and YT tutorial running on localhost, I'm getting an Error 500 on trying to click "Connect Wallet"

I forked this repository and had only changed the `.env` file as below

![.env file](https://user-images.githubusercontent.com/29685404/187269876-6fa2380a-5fba-4236-b75c-8ebf08f26b74.png)

Below are some snippets of the errors

![Connect Wallet error](https://user-images.githubusercontent.com/29685404/187269966-179b20db-13e2-47d0-86d6-7a9b5bed1805.png)

/api/auth/request-message HTTP/1.1
![Error 500](https://user-images.githubusercontent.com/29685404/187270008-4fa8eb4a-7cfe-4abb-98d5-bc470a573316.png)

**Comment by Y0moo** [comment]
Hey @niomartinez! Sorry for the typo, fixed in README. It should be `.env.local`

**Comment by niomartinez** [comment]
Hi @Y0moo yes sure, anyway, I didn't changed it to `.env.local` however, the fix had something to do with `NEXTAUTH_SECRET` the first time i got it from the url, it might have expired or somehow it did not work, I tried generating another using the link provided https://generate-secret.now.sh/32 and issue was solved now.
