### ISSUE TITLE
json parse bug

### ISSUE THREAD

**Issue by FullstackWEB-developer** [ethereum-boilerplate/ethereum-boilerplate#183]
![image](https://user-images.githubusercontent.com/92151436/190119676-62086177-54c1-4589-9f8f-1df600558b4b.png)
I got this error in sepolia chain
![image](https://user-images.githubusercontent.com/92151436/190121813-3d195c68-a4f5-4509-bcbf-ee2c1aa4b91c.png)

**Comment by johnvsnagendra** [comment]
Only these blockchains are currently supported by Auth API. So probably this will be auto-resolved when Sepolia (11155111) is supported with Auth API.
<img width="142" alt="image" src="https://user-images.githubusercontent.com/15834299/192711592-70b544cf-14ee-46c9-b6e5-3d4397b6792e.png">

**Comment by FullstackWEB-developer** [comment]
thanks
