### ISSUE TITLE
Set custom gas for active web3 used (ie: useWeb3Contract())

### ISSUE THREAD

**Issue by ss5nathan** [ethereum-boilerplate/ethereum-boilerplate#19]
Is there a way to set user defined gas (for example to provide the user with slow, average, fast) gas options? If so, what would be the best way to do so!

Hope I am not missing something on my end that should be straightforward.

**Comment by ss5nathan** [comment]
As an add-on to this, is there a good way to access the underlying web3 provider with this boilerplate to set gas or other parameters {from:0x, value:123, gas: 123}

**Comment by Y0moo** [comment]
Hi @ss5nathan ! You can't set it if you use `useWeb3ExecuteFunction()` now. You can get a wev3 provider from Moralis:

```
import { useMoralis } from "react-moralis" 

const { web3 } = useMoralis
```

Take a look at https://github.com/MoralisWeb3/react-moralis#web3

**Comment by ss5nathan** [comment]
Ah, thank you! Exactly what I was looking for. Love the work your team is doing on this!

**Comment by Y0moo** [comment]
Happy BUIDLing
