### ISSUE TITLE
The engine "node" is incompatible with this module

### ISSUE THREAD

**Issue by aveliino88** [ethereum-boilerplate/ethereum-boilerplate#199]
![Скриншот 19-02-2023 173327](https://user-images.githubusercontent.com/89843361/219958078-a59deaaa-c55e-4a87-b0a9-566869492821.jpg)
Can't deploy on Vercel

**Comment by Y0moo** [comment]
Hey @aveliino88! Please pull the latest changes. It should be fixed now.

**Comment by arpitgoyall** [comment]
I cloned this repository today and it is giving the same error.
