### ISSUE TITLE
Can't connect to local dev chain (Failed running cloud function getTokenBalances for user undefined)

### ISSUE THREAD

**Issue by damiensawyer** [ethereum-boilerplate/ethereum-boilerplate#23]
Hi, we're unable to connect Moralis to a local dev chain. We posted a question [here](https://forum.moralis.io/t/failed-running-cloud-function-gettokenbalances-for-user-undefined/4039) and were told "web3api calls don’t work with local dev chain". 

Full post below

Thanks :-)

--------------

We are using the Etherium boilerplate project here https://github.com/ethereum-boilerplate/ethereum-boilerplate (lets call this EBP)
We are running Ganash locally and have set up the frp reverse proxy. When we look in the moralis dashboard “devchain proxy server”, we show as “connected”.

In metamask we have imported an account using a private key from Ganash. Metamask is showing that we have 100 Eth in the account. We then use this account to authenticate with EBP.

The issue occurs when we navigate to the “Wallet” tab in EBP. We see a 400 error from the getTokenBalanes endpoint.

The curl genreated by Chrome is:

curl ‘https://42sf9cpyfott.usemoralis.com:2053/server/functions/getTokenBalances’
-H ‘Connection: keep-alive’
-H ‘Pragma: no-cache’
-H ‘Cache-Control: no-cache’
-H ‘sec-ch-ua: “Google Chrome”;v=“95”, “Chromium”;v=“95”, “;Not A Brand”;v=“99”’
-H ‘Accept: application/json’
-H ‘DNT: 1’
-H ‘Content-Type: application/json’
-H ‘sec-ch-ua-mobile: ?0’
-H ‘User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36’
-H ‘sec-ch-ua-platform: “Windows”’
-H ‘Origin: http://localhost:3000/’
-H ‘Sec-Fetch-Site: cross-site’
-H ‘Sec-Fetch-Mode: cors’
-H ‘Sec-Fetch-Dest: empty’
-H ‘Referer: http://localhost:3000/’
-H ‘Accept-Language: en-AU,en;q=0.9,en-US;q=0.8’
–data-raw ‘{“address”:“0xce24fa85beea429ef601534151db39f0597c81cd”,“chain”:“0x539”}’
–compressed

When we look in the Moralis dashboard we see the following error.

Error received
2021-11-02T01:29:12.296Z - Failed running cloud function getTokenBalances for user undefined with:
Input: {“address”:“0xce24fa85beea429ef601534151db39f0597c81cd”,“chain”:“0x539”}
Error: {“message”:"[object Object]",“code”:141}

**Comment by ivan-liljeqvist** [comment]
Yes we will add support for it for some endpoints that don’t require indexing 🙌

**Comment by damiensawyer** [comment]
Thanks @ivan-liljeqvist . 
Do you mind if I ask a question? 
I'm a complete noob at dApps and still trying to get my head around what's going on. It's hard for me to tell the difference between a bug in a tool I'm using or a gap in my understanding. 

Untill you add support for local dev chain, what network do you suggest I use with this project? Kovan? Rinkby? Something else?

Thanks very much.

**Comment by ivan-liljeqvist** [comment]
And then see how we can add the rest

**Comment by ivan-liljeqvist** [comment]
I would use Rinkeby as it’s very active testnet - relatively easy to get test coins etc

**Comment by brooksmorgan** [comment]
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (P:\React_Dev\ethereum-boilerplate\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (P:\React_Dev\ethereum-boilerplate\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (P:\React_Dev\ethereum-boilerplate\node_modules\webpack\lib\NormalModule.js:471:10)
    at P:\React_Dev\ethereum-boilerplate\node_modules\webpack\lib\NormalModule.js:503:5
    at P:\React_Dev\ethereum-boilerplate\node_modules\webpack\lib\NormalModule.js:358:12
    at P:\React_Dev\ethereum-boilerplate\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (P:\React_Dev\ethereum-boilerplate\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (P:\React_Dev\ethereum-boilerplate\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
P:\React_Dev\ethereum-boilerplate\node_modules\react-scripts\scripts\start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (P:\React_Dev\ethereum-boilerplate\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (P:\React_Dev\ethereum-boilerplate\node_modules\webpack\lib\NormalModule.js:417:16)
    at P:\React_Dev\ethereum-boilerplate\node_modules\webpack\lib\NormalModule.js:452:10
    at P:\React_Dev\ethereum-boilerplate\node_modules\webpack\lib\NormalModule.js:323:13
    at P:\React_Dev\ethereum-boilerplate\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at P:\React_Dev\ethereum-boilerplate\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (P:\React_Dev\ethereum-boilerplate\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at P:\React_Dev\ethereum-boilerplate\node_modules\react-scripts\node_modules\babel-loader\lib\index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}



i have been getting this errors. Any quick help
