### ISSUE TITLE
Missing Dependencies/ Compile Issue

### ISSUE THREAD

**Issue by Starblue0** [ethereum-boilerplate/ethereum-boilerplate#24]
"Yarn" has been loaded with terminal. Issue Happens when Running "npm start" 

NPM Start: Missing Dependencies/ Compilation with Warning. 

___________________________________________________________________________________________________________________________________
Compiled with warnings.

src\components\AddressInput.jsx
  Line 14:6:  React Hook useEffect has missing dependencies: 'props' and 'validatedAddress'. Either include them or remove the dependency array. However, 'props' will change when *any* prop changes, so the preferred fix is to destructure the 'props' object outside of the useEffect call and refer to those specific props inside useEffect  react-hooks/exhaustive-deps

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.
___________________________________________________________________________________________________________________________________

**Comment by Y0moo** [comment]
Hi! This is just a warning, you can ignore it. We will fix it in the next versions.

**Comment by jennyfromtheblockchains** [comment]
I had the same issue. Just copy/paste `// eslint-disable-next-line` to right above line 14 (which should be `}, [address]);`) and it should build with no issues.

**Comment by irpheus** [comment]
Also having this error. Adding  // eslint-disable-next-line doesnt work. Please assist
