### ISSUE TITLE
Error when accessing Localhost:3000

### ISSUE THREAD

**Issue by Starblue0** [ethereum-boilerplate/ethereum-boilerplate#25]
Error when accessing localhost for development, Saying no Context provider. 
This is a fresh download and instance of VS and the Boilerplate being ran on the local host. 

Last issue gave a Compile error and  missing Dependencies error: [https://github.com/ethereum-boilerplate/ethereum-boilerplate/issues/24](url)
___

![NoMoralisContextProviderError1](https://user-images.githubusercontent.com/89170602/140587680-d7c1e094-8428-4f77-a63c-69209cd09b52.png)

______________

Below is what I copied from the Photo
_
>NoMoralisContextProviderError: Make sure to only call useMoralis within a  <MoralisProvider>
NoMoralisContextProviderError.ReactMoralisError [as constructor]
C:/Users/Owner/Desktop/src/Errors.ts:4
  1 | export class ReactMoralisError extends Error {
  2 |   static isReactMoraliserrpr = true;
  3 | 
> 4 |   constructor(message: string) {
  5 |     super(`[react-moralis]: ${message}`);
  6 |     this.name = "ReactMoralisError";
  7 |     this.message = message;
View compiled
new NoMoralisContextProviderError
C:/Users/Owner/Desktop/src/Errors.ts:12
   9 | }
  10 | 
  11 | export class NoMoralisContextProviderError extends ReactMoralisError {
> 12 |   constructor(message: string) {
  13 |     super(message);
  14 |     this.name = "NoMoralisContextProviderError";
  15 |   }
View compiled
useMoralis
C:/Users/Owner/Desktop/src/hooks/useMoralis/useMoralis.ts:9
   6 | const moralisContext = useContext(MoralisContext);
   7 | 
   8 | if (!moralisContext) {
>  9 |   throw new NoMoralisContextProviderError(
     | ^  10 |     "Make sure to only call useMoralis within a  <MoralisProvider>",
  11 |   );
  12 | }
View compiled
QuickStart
C:/Users/Owner/Desktop/ethereum-boilerplate-main/src/components/QuickStart.jsx:26
  23 | };
  24 | 
  25 | export default function QuickStart({ isServerInfo }) {
> 26 |   const { Moralis } = useMoralis();
  27 | 
  28 |   const isInchDex = useMemo(
  29 |     () => (Moralis.Plugins?.oneInch ? true : false),
View compiled
▶ 17 stack frames were collapsed.
Module.<anonymous>
C:/Users/Owner/Desktop/ethereum-boilerplate-main/src/index.js:32
  29 | };
  30 | 
  31 | /** Get your free Moralis Account https://moralis.io/ */
> 32 | ReactDOM.render(
  33 |   // <React.StrictMode>
  34 |   <Application />,
  35 |   // </React.StrictMode>,
View compiled
Module../src/index.js
http://localhost:3000/static/js/main.chunk.js:8158:30
__webpack_require__
C:/Users/Owner/Desktop/ethereum-boilerplate-main/webpack/bootstrap:851
  848 | 
  849 | __webpack_require__.$Refresh$.init();
  850 | try {
> 851 | 	modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  852 | } finally {
  853 | 	__webpack_require__.$Refresh$.cleanup(moduleId);
  854 | }
View compiled
fn
C:/Users/Owner/Desktop/ethereum-boilerplate-main/webpack/bootstrap:150
  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {
View compiled
1
http://localhost:3000/static/js/main.chunk.js:8536:18
__webpack_require__
C:/Users/Owner/Desktop/ethereum-boilerplate-main/webpack/bootstrap:851
  848 | 
  849 | __webpack_require__.$Refresh$.init();
  850 | try {
> 851 | 	modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  852 | } finally {
  853 | 	__webpack_require__.$Refresh$.cleanup(moduleId);
  854 | }
View compiled
checkDeferredModules
C:/Users/Owner/Desktop/ethereum-boilerplate-main/webpack/bootstrap:45
  42 | 	}
  43 | 	if(fulfilled) {
  44 | 		deferredModules.splice(i--, 1);
> 45 | 		result = __webpack_require__(__webpack_require__.s = deferredModule[0]);
     | ^  46 | 	}
  47 | }
  48 | 
View compiled
Array.webpackJsonpCallback [as push]
C:/Users/Owner/Desktop/ethereum-boilerplate-main/webpack/bootstrap:32
  29 | 	deferredModules.push.apply(deferredModules, executeModules || []);
  30 | 
  31 | 	// run deferred modules when all chunks ready
> 32 | 	return checkDeferredModules();
     | ^  33 | };
  34 | function checkDeferredModules() {
  35 | 	var result;
View compiled
(anonymous function)
http://localhost:3000/static/js/main.chunk.js:1:93
________________

**Comment by Y0moo** [comment]
Hi! have you installed all dependencies `npm install` and started the app by `npm run start`?

**Comment by Starblue0** [comment]
I have tried npm install and npm run start
I have tried yarn and npm start

Redownloaded the boilerplate again & Unzipped the Boilerplate folder to my desktop
then I opened the folder in VScode and Retried steps Above & same issue still occurs. 

I was following this Tutorial: 
Building a Defi Dashboard on Avalanche ❄️ Dapp Programming Tutorial:
https://www.youtube.com/watch?v=8mjJUNYTqTc&t=197s

Link is marked starting at 3:17(197s) for the Video.

**Comment by Y0moo** [comment]
@Starblue0 What version of Node.js do you have?

**Comment by Starblue0** [comment]
@Y0moo I am running Nodejs v16.13.0

**Comment by Y0moo** [comment]
@Starblue0 Please follow https://github.com/ethereum-boilerplate/ethereum-boilerplate#-quick-start 
Don't forget to rename` .env.example` to `.env` before startign the App.

**Comment by Neaxic** [comment]
Im having the same issue. Did 1:1 the quick start guide. I really dont see where i stepped wrong. Im nodejs version 16.8.0.
Only did the QuickStart, haven't manipulated anything other than the .env. - I cant run project. Completely same error log.

Im on windows

**Comment by malawadd** [comment]
> 

had the same issue, just did  restarted my pc  and it fixed

**Comment by Neaxic** [comment]
Still having same issue

**Comment by KomengTech** [comment]
Found a way to solve it. Just needed to install Live Server extension on Visual Studio Code.

**Comment by MashmallowWoR** [comment]
i still have the same issue even after restart computer and installed Live Server extension. anything else i should check?
