### ISSUE TITLE
Token not set in transfer.jsx when using wallet. 

### ISSUE THREAD

**Issue by damiensawyer** [ethereum-boilerplate/ethereum-boilerplate#26]
Hi, 

We're trying to get our heads around using the wallet. 

We've connected our project to Rinkby in Metamask and, on the wallet screen, can see that we have a test ether balance. 

When we try to transfer though we get nothing. On debugging we notice that the Transfer button is enabled because the ```token``` state is not set. 

If we make this change:
```const [token, setToken] = useState("eth");```
... we see an Eth symbol appear and the button becomes clickable. On clicking though, more errors are seen. 

Can someone please explain how we're supposed to be using this? I'm wondering if there is another step we're missing which would have set the token hook. 

Thanks for your help :-)

**Comment by Y0moo** [comment]
Hi @damiensawyer ! Currently, the wallet supports only ERC20 token transfers. We'll push today version with native transfers

**Comment by damiensawyer** [comment]
Thanks @Y0moo.
