### ISSUE TITLE
Connect Wallet Button returning Connector not found.

### ISSUE THREAD

**Issue by tatumalgorand** [ethereum-boilerplate/ethereum-boilerplate#268]
Hi,

thank you very much for this great code.
I have a slight issue though. When I am on a mobile device and I press the Wallet Connect button, I receive an error message saying;
"Oops something went wrong, Connector not found" . 
Could anyone help me get this button working as I am not a web3 expert and I would like to know how to connect this boilerplate to mobile websites.

I have managed to get individual buttons working elsewhere but I would like for it to work with this boilerplate.

Thanks in advance
Danny

**Comment by tatumalgorand** [comment]
I can run a deeplink to metamask but its not really what I wanted to do . The connect button works once the website is opened with metamask browser or trust browser. 
Also the Mobile styling of the boilerplate seems to be somewhat off. The menu is too wide for mobile devices so when the website initially loads , the connect button is out of view. Is it possible to change some of the styling to give a better mobile view and also for the connect wallet button to work on mobile devices ???

Again I am sorry to ask what seem to be simple questions but until you know the answer then it is hard.

Thanks again

**Comment by uaktags** [comment]
@tatumalgorand not sure if you moved on from here, but the issue is because it requires HTTPS to work.

Really surprised that the creator would enable auto-closing of issues rather than responding to them
