### ISSUE TITLE
suggestion: change repo type

### ISSUE THREAD

**Issue by JiangWeixian** [ethereum-boilerplate/ethereum-boilerplate#28]
maybe set repo as `template repo`

**Comment by ivan-liljeqvist** [comment]
where is this et?

**Comment by JiangWeixian** [comment]
> where is this set?

![image](https://user-images.githubusercontent.com/6839576/148214364-55fb42da-fb5a-4def-a7cf-f33f93638d77.png)

after set repo as template, will see `use this template` button

![image](https://user-images.githubusercontent.com/6839576/148214405-a92e20e5-64ac-444b-89dd-f5c4161c8443.png)

**Comment by Y0moo** [comment]
@ivan-liljeqvist can you see this? Looks like I have not access to this
