### ISSUE TITLE
DEX-decimals issue

### ISSUE THREAD

**Issue by beyondthecode-bc** [ethereum-boilerplate/ethereum-boilerplate#35]
If you try to SWAP from (doesn't matter the coin/token) with the value 0.0012/0.0013, it crashes with:

Error: [number-to-bn] while converting number "0x0.004189374bc6a7f" to BN.js instance, error: invalid number value. Value must be an integer, hex string, BN or BigNumber instance. Note, decimals are not supported. Given value: "0x0.004189374bc6a7f"

![image](https://user-images.githubusercontent.com/62696158/142730977-17fee3ff-333b-4bda-9e3b-eb5c1363cad7.png)

**Comment by BanalitoRaulito** [comment]
Hey @beyondthecode-bc 

Could you tell me what value Moralis.Utils.Token returns?
Because it can not be "0.0012/0.0013". That amount has to an integer.
Please also let me know what values are in params object?

**Comment by beyondthecode-bc** [comment]
Please find the live test of the Swap issue:
https://we.tl/t-YElP7CMiVO
---
I understand what you are trying to say but, if I try values like 0.00012, it works. Only 0.0012 and so on.. crashes the DEX. Not sure what can cause this issue

**Comment by Y0moo** [comment]
Sorry, @beyondthecode-bc I deleted your comment because of the link. It's not secure

**Comment by Y0moo** [comment]
I don't see any problems
![image](https://user-images.githubusercontent.com/78314301/143086561-c4f957b5-7443-4044-911e-09c3eae327fb.png)

**Comment by Y0moo** [comment]
make sure you are running the latest build

**Comment by beyondthecode-bc** [comment]
@Y0moo select a Token first of all.. most important :)
I understand, hope that you've saw the issue replicating. If you have a different website where I can upload it... let me know

**Comment by Y0moo** [comment]
@BanalitoRaulito I was able to reproduce the issue
