### ISSUE TITLE
There are compile errors after converting to TypeScript.

### ISSUE THREAD

**Issue by sam-goodwin** [ethereum-boilerplate/ethereum-boilerplate#45]
I think it would be better if moralis published boiler plate examples in TypeScript instead of JS. JS is simply bad practice and this repo seems to be a perfect example of why.

I cloned this repo and converted it to typescript. This immediately revealed a bunch of errors. 

Some of the imports for local files are not using relative file paths. Example below, should be `../helpers/networks`.
https://github.com/ethereum-boilerplate/ethereum-boilerplate/blob/0632765e6d087904f87b193f96dff637faab6019/src/components/NFTBalance.jsx#L5

The `useMoralis()` returns the wrong type.
![image](https://user-images.githubusercontent.com/38672686/143722624-f667e0b7-9a46-438d-8243-20c844654e51.png)

Trying to call `transfer` on `typeof Moralis` is wrong. I think the framework is returning the wrong type?
![image](https://user-images.githubusercontent.com/38672686/143722627-30dfafdd-43d1-4051-8d7a-ad32f4e7be98.png)

Is this meant to return `Moralis.Web3`? That's the only type I could find with the `transfer` function.

According to TypeScript, `fontWeight: "500"` is not supported.
https://github.com/ethereum-boilerplate/ethereum-boilerplate/blob/0632765e6d087904f87b193f96dff637faab6019/src/components/Account.jsx#L51

```
Type '"500"' is not assignable to type 'FontWeight'.ts(2322)
index.d.ts(2002, 3): The expected type comes from property 'fontWeight' which is declared here on type 'CSSProperties'
```

There's a comment here admitting that the second argument is missing. This is a type-error which would suggest to me that there is either a runtime error or the core `FromWei` function is mis-typed.

https://github.com/ethereum-boilerplate/ethereum-boilerplate/blob/0632765e6d087904f87b193f96dff637faab6019/src/components/NativeTransactions/NativeTransactions.jsx#L37-L38

Looks like there are many other bugs that I won't bother to document. Point being ... there seems to be a quality problem with the Moralis types and examples. This hurts adoption and also starts off newcomers in a bad place. Please prioritize proper use of types for the framework. Types teach people how to use your framework and protect them from mis-using. Publishing JS-only boilerplate is not good in the long-run IMO.

**Comment by Y0moo** [comment]
Hi @sam-goodwin 

Thank you for your feedback. This boilerplate is on top of Vanilla Js because not all developers. especially newbies work with typescript. Typescript boilerplate is in process

**Comment by gjj** [comment]
Hey! Is there a branch for the TypeScript version?
