### ISSUE TITLE
[node >= v17] ERR_OSSL_EVP_UNSUPPORTED

### ISSUE THREAD

**Issue by oscario2** [ethereum-boilerplate/ethereum-boilerplate#48]
As of [v17](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V17.md#openssl-30) `node` have deprecated a few openssl algorithms which causes issues with `webpack`.  

It can be resolved by adding the `--openssl-legacy-provider` flag in `yarn start` or the environment variable.  

Alternatively, consider using `output: { hashFunction: 'xxhash64' }` if you've got plans on upgrading webpack (or react-scripts) as current `react-scripts/config/webpack.config.js` will throw `Digest method not supported`

**Comment by kindere68** [comment]
It should always be supported if code cvtsv is entered properly into suppository

**Comment by Gizmotronn** [comment]
@oscario2 a quick solution now (I had the same problem) is just installing Node v16, I used the latest release previously and ran into the same error :)

**Comment by tarbusca** [comment]
I am on Node v17.3.0 and facing same issue.  Using the flag --openssl-legacy-provider didn't help.
Any other solution ?

**Comment by ashajjar** [comment]
probably you should consider using LTS version I was on latest version when I faced the same issue, but now I downgraded to LTS (luckily I have nvm 😆 )
