### ISSUE TITLE
Having alot of issues with a code and node-modules

### ISSUE THREAD

**Issue by GodSlayer436** [ethereum-boilerplate/ethereum-boilerplate#51]
I am having a lot of issues with the code and node_modules, i even reinstalled nodejs, node_modules, the repo and did everything you can think of: 
Error: useMoralisDapp must be used within a MoralisDappProvider
useMoralisDapp
src/providers/MoralisDappProvider/MoralisDappProvider.js:41
  38 | function useMoralisDapp() {
  39 |   const context = React.useContext(MoralisDappContext);
  40 |   if (context === undefined) {
> 41 |     throw new Error("useMoralisDapp must be used within a MoralisDappProvider");
  42 |   }
  43 |   return context;
  44 | }
View compiled
useNFTBalance
src/hooks/useNFTBalance.js:8
   5 | 
   6 | export const useNFTBalance = (options) => {
   7 |   const { account } = useMoralisWeb3Api();
>  8 |   const { chainId } = useMoralisDapp();
   9 |   const { resolveLink } = useIPFS();
  10 |   const [NFTBalance, setNFTBalance] = useState([]);
  11 |   const {
View compiled
NFTBalance
src/components/NFTBalance.jsx:24
  21 | };
  22 | 
  23 | function NFTBalance() {
> 24 |   const { NFTBalance } = useNFTBalance();
  25 |   const { chainId, marketAddress, contractABI } = useMoralisDapp();
  26 |   const { Moralis } = useMoralis();
  27 |   const [visible, setVisibility] = useState(false);
View compiled
▶ 17 stack frames were collapsed.
Module.<anonymous>
src/index.js:30
  27 |   }
  28 | };
  29 | 
> 30 | ReactDOM.render(
  31 |   // <React.StrictMode>
  32 |   <Application />,
  33 |   // </React.StrictMode>,
View compiled
Module../src/index.js
http://localhost:3001/ethereum-boilerplate/static/js/main.chunk.js:3947:30
__webpack_require__
/home/godslayer436/Documents/GitHub/ethereum-boilerplate/webpack/bootstrap:851
  848 | 
  849 | __webpack_require__.$Refresh$.init();
  850 | try {
> 851 | 	modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  852 | } finally {
  853 | 	__webpack_require__.$Refresh$.cleanup(moduleId);
  854 | }
View compiled
fn
/home/godslayer436/Documents/GitHub/ethereum-boilerplate/webpack/bootstrap:150
  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {
View compiled
1
http://localhost:3001/ethereum-boilerplate/static/js/main.chunk.js:4331:18
__webpack_require__
/home/godslayer436/Documents/GitHub/ethereum-boilerplate/webpack/bootstrap:851
  848 | 
  849 | __webpack_require__.$Refresh$.init();
  850 | try {
> 851 | 	modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  852 | } finally {
  853 | 	__webpack_require__.$Refresh$.cleanup(moduleId);
  854 | }
View compiled
checkDeferredModules
/home/godslayer436/Documents/GitHub/ethereum-boilerplate/webpack/bootstrap:45
  42 | 	}
  43 | 	if(fulfilled) {
  44 | 		deferredModules.splice(i--, 1);
> 45 | 		result = __webpack_require__(__webpack_require__.s = deferredModule[0]);
     | ^  46 | 	}
  47 | }
  48 | 
View compiled
Array.webpackJsonpCallback [as push]
/home/godslayer436/Documents/GitHub/ethereum-boilerplate/webpack/bootstrap:32
  29 | 	deferredModules.push.apply(deferredModules, executeModules || []);
  30 | 
  31 | 	// run deferred modules when all chunks ready
> 32 | 	return checkDeferredModules();
     | ^  33 | };
  34 | function checkDeferredModules() {
  35 | 	var result;
View compiled
(anonymous function)
http://localhost:3001/ethereum-boilerplate/static/js/main.chunk.js:1:93
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.  Click the 'X' or hit ESC to dismiss this message.

**Comment by toledoroy** [comment]
This seems like the error that used to come up when the .env file was missing.
