### ISSUE TITLE
[Ubuntu]: Fix for source map paths

### ISSUE THREAD

**Issue by oscario2** [ethereum-boilerplate/ethereum-boilerplate#59]
in `node_modules/react-scripts/config/webpack.config.js` change `sourceMaps: shouldUseSourceMap` to `sourceMaps: false` to allow proper paths for debugging

One can use `customize-cra` to override the config without ejecting the project.

From:
![from](https://user-images.githubusercontent.com/6534774/146440173-0938bde4-e568-47ec-a392-c15490498752.PNG)

To:
![to](https://user-images.githubusercontent.com/6534774/146440222-2137f6a7-035a-471b-8a39-a499aeb39353.PNG)

**Comment by mdatsev** [comment]
```js
const shouldUseSourceMap = process.env.GENERATE_SOURCEMAP !== 'false';
```
Therefore you can add `GENERATE_SOURCEMAP=false` to .env instead.
