### ISSUE TITLE
Some components are not rendering

### ISSUE THREAD

**Issue by zakjanzi** [ethereum-boilerplate/ethereum-boilerplate#60]
Some components are not rendering partially (such as the wallet section) and some don't render entirely (such as the fiat section)

Console log: https://media.discordapp.net/attachments/691025042343198740/921350541509029888/unknown.png?width=1202&height=676

I'm not very technical but based on some basic researching I think this has something to do with ReactDOM

![wallet section](https://user-images.githubusercontent.com/82332662/146532694-88bd77f7-7be7-4843-80c0-fe9eeac82c6e.PNG)
![transfers](https://user-images.githubusercontent.com/82332662/146532703-8a2e83db-0c3b-48a4-8605-ad1b24c015ea.PNG)
![onramper](https://user-images.githubusercontent.com/82332662/146532705-de20ccaa-a13a-444d-b3d5-6d7a7717c788.png)
.

**Comment by omnaladkar** [comment]
is it open?

**Comment by zakjanzi** [comment]
> is it open?

Is what open?

**Comment by zakjanzi** [comment]
The components in question load as soon as you authenticate - other than that there are no issues.
