### ISSUE TITLE
Fix name of file build/contracts/Metacoin.json in Truffle/scripts/contractInfo.js

### ISSUE THREAD

**Issue by dguard** [ethereum-boilerplate/ethereum-boilerplate#72]
![image](https://user-images.githubusercontent.com/1911516/147660899-fc58e089-b16b-419f-829c-742663dcd7f9.png)

**Comment by ivan-liljeqvist** [comment]
please make a merge request if you know how to fix

**Comment by dguard** [comment]
@ivan-liljeqvist 
![image](https://user-images.githubusercontent.com/1911516/148209770-e5cbb7cb-51a7-4320-860e-519e0e7ed397.png)
