### ISSUE TITLE
Add PWA Support

### ISSUE THREAD

**Issue by YosephKS** [ethereum-boilerplate/ethereum-boilerplate#79]
In order to improve the UX and performance of Ethereum Boilerplate, adding PWA functionality will be a great feature to be added. This will in turn make Ethereum Boilerplate-based Web dApps to be available offline (frontend cached service worker, but still can't connect to backend functionality) and feel more closer to native mobile apps.

**Comment by ivan-liljeqvist** [comment]
nice please provide implementation example 🙌 thanks

**Comment by YosephKS** [comment]
NOTE: PWA Support Added 🚀
