### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by nschwermann** [ethereum-boilerplate/ethereum-boilerplate#8]
Ran the following commands

```
git clone https://github.com/ethereum-boilerplate/ethereum-boilerplate.git
cd ethereum-boilerplate
yarn install
yarn start
```

Got the following error:

./src/components/NFTBalance.jsx
Attempted import error: 'getExplorer' is not exported from 'helpers/networks'.

**Comment by nschwermann** [comment]
resolved by adding 

```
export const getExplorer = (chain) => networkConfigs[chain]?.blockExplorerUrl
```

to networks.js but there several more errors occur.

**Comment by Y0moo** [comment]
Thank you! Fixed on new versions
