### ISSUE TITLE
localhost is white!!!

### ISSUE THREAD

**Issue by smkplus** [ethereum-boilerplate/ethereum-boilerplate#84]
I followed the steps to start working with Moralis but It doesn't work

![image](https://user-images.githubusercontent.com/16706911/148647345-3047c27d-c2d3-4597-8a48-c100eac87f9b.png)

![image](https://user-images.githubusercontent.com/16706911/148647325-63f68b32-170a-4315-8581-f197659c39e6.png)

**Comment by ivan-liljeqvist** [comment]
for help https://forum.moralis.io/t/ethereum-boilerplate-questions
