### ISSUE TITLE
Authentication doesn't work

### ISSUE THREAD

**Issue by orrburgel** [ethereum-boilerplate/ethereum-boilerplate#85]
1) When you click Authenticate and choose MetaMask and then click "Sign" in MetaMask, nothing happens, unlike the GIF where you can see  your address instead of the Authenticate button after you login.
I tested multiple times, disabled ad blocker, on the demo version at: https://ethereum-boilerplate.github.io/ethereum-boilerplate
![image](https://user-images.githubusercontent.com/41600149/148665287-e82bc5b2-1aa2-49dc-bf75-161bcbe342eb.png)

2) Unable to switch back to Kovan Testnet, tried to refresh, tried multiple times, you simply can't click Kovan Testnet, although the default setting was Kovan and I switched it to Ethereum and now it seems stuck on it (will be glad for a fix)
![image](https://user-images.githubusercontent.com/41600149/148665282-dbe6d325-d525-4ea0-bdb6-6c76f4a17746.png)

3) Console errors:
![image](https://user-images.githubusercontent.com/41600149/148665226-5d0462c8-11a6-468d-babc-6b62196eb5f0.png)

4) More console errors as soon as you authenticate:
![image](https://user-images.githubusercontent.com/41600149/148665263-fe1aae9c-81af-4bb0-8ce1-893cb06a2c06.png)

5) Refreshing inner pages leads to 404.
Example 404 link: https://ethereum-boilerplate.github.io/quickstart
![image](https://user-images.githubusercontent.com/41600149/148665294-7b79c2ed-97ab-4d07-aa2c-66678419afa4.png)

**Comment by orrburgel** [comment]
I can fix number 5 and commit my changes but I need help with the rest, seems like the project is malfunctioning at it's very core.

**Comment by ivan-liljeqvist** [comment]
Run repo locally instead to test 

Seems that demo server shut down
Notified the devs

**Comment by orrburgel** [comment]
@ivan-liljeqvist thanks for the super fast response I'm glad to hear the local version might work, I'll try

**Comment by orrburgel** [comment]
I tried to run it locally and faced the same issue plus this one, even if you open it in incognito the button will look unclickable (doesn't have a cursor:pointer; css) and it has this not round image of uniswap for some reason:
![image](https://user-images.githubusercontent.com/41600149/148665953-a3fd855a-ccc2-4633-8082-f21600f09124.png)

Console errors:
![image](https://user-images.githubusercontent.com/41600149/148665923-16ccf735-6cdc-4031-89ba-a5e68c1e8fea.png)

**Comment by orrburgel** [comment]
I actually didn't run it locally, I ran yarn build and uploaded the build to Moralis and this is where my test environment is, and where I took the images from, but if you just follow the instructions at https://ethereumboilerplate.com/
![image](https://user-images.githubusercontent.com/41600149/148666099-d65247cf-b572-4c27-b1ef-826b6681f2cf.png)

You end up at a blank page:
![image](https://user-images.githubusercontent.com/41600149/148666102-75d8195b-1c25-46c5-ba9e-021a1411d0f7.png)

Even navigating manually to a known page leads to a blank page:
![image](https://user-images.githubusercontent.com/41600149/148666109-f8d35c0c-327f-49c5-919c-73d12003b1f1.png)

**Comment by orrburgel** [comment]
Tried again using the version from 13 days ago (before the version 2 days ago) and I no longer see a blank page but still the same issue in both the local and remote versions:
![image](https://user-images.githubusercontent.com/41600149/148666640-b8aad6e7-124d-47c5-9f53-83123a368a26.png)
![image](https://user-images.githubusercontent.com/41600149/148666643-4f69bfa5-0563-4fd6-a7c6-992ef31723a6.png)
Notice that this time the button looks different, I guess since I used a different version, origin: https://github.com/ethereum-boilerplate/ethereum-boilerplate/tree/087748dfd2c6e8e368becff14ebfb2cf9e39b3b1

**Comment by orrburgel** [comment]
Apparently I did something wrong, I set it up like this:
```
REACT_APP_MORALIS_APPLICATION_ID = entered url
REACT_APP_MORALIS_SERVER_URL = entered id
```
I'm trying again locally using this tutorial: https://www.youtube.com/watch?v=WZWCzsB1xUE

**Comment by Y0moo** [comment]
The boilerplate itself works correctly. The demo server shut down, so we need to update it for the demo. 
The navigation may not work correctly(pages will not load after the refresh)  because of GitHub pages, need to check if it's possible to fix

**Comment by Y0moo** [comment]
Please let us know how it works for you @orrburgel

**Comment by orrburgel** [comment]
@Y0moo Hey, Thank you for your reply, I will be glad if we can get to the bottom of this, I'm still having the same issue both on the demo and the local version, after signing in with meta mask nothing happens and it remains like this:
![image](https://user-images.githubusercontent.com/41600149/148676602-848a38d0-d241-403a-bcf7-0953d45201d1.png)
with the following console errors:
![image](https://user-images.githubusercontent.com/41600149/148676606-7252edd1-f865-48a6-a585-88cfbb4d5f8e.png)

**Comment by Y0moo** [comment]
@orrburgel please check your server info. I can see here the error about the problem with connecting to the server. Also, I don't see any logs for server with the subdomain `eytxv4rr5p...` looks like you provided Server Details not correctly (appId and serverUrl)
