### ISSUE TITLE
(Bug) Closing and reopening the browser leads to inability to login with any wallet - Replicable

### ISSUE THREAD

**Issue by orrburgel** [ethereum-boilerplate/ethereum-boilerplate#87]
#### Issue description

After I login with my wallet and then close the browser and reopen it -> I become logged out and when trying to login again with one of the wallets nothing happens and the console says `chain null`

#### Steps to reproduce the issue

1. Run the project locally (I also deployed it to moralis and tested locally, on chrome)
2. Login with Metamask
3. Refresh
4. Stay logged in
5. Close browser/Restart PC - Make sure in task manager chrome is fully closed since running PWA's or chrome in the background will prevent this bug from happening
6. Open the browser
7. Navigate to the server address (Same bug if you leave the tab open or close it before you shutdown the browser\pc)
8. You will now need to reauthenticate (and the console is filled with chain null console logs coming from Chains.jsx, unlike normal runs)
9. Try to login with Metamask - Nothing happens
10. Open DevTools  - Whenever you click on a wallet login button it will log -> `chain null`

#### What's the expected result?

When I reopen the browser I expect it to remain logged in, or notify me of the lost connection and ask to reconnect my wallet, without refreshing the browser a few times to get login to work again

-

#### What's the actual result?

I login, close the browser, reopen it, and I can't login unless I refresh a few times, and then I need to relogin - all within the same minute

-

#### Additional details / screenshot

1. Login with Metamask: (I did some CSS but this is happening before I did any changes)
![image](https://user-images.githubusercontent.com/41600149/148709041-18a03522-b7ae-4c63-a989-a3f76125fcf3.png)

2. Close browser and reopen it:
![image](https://user-images.githubusercontent.com/41600149/148709053-a5fe7ff0-f8f7-4e9d-8316-ae48d226d66b.png)
Console at that state:
![image](https://user-images.githubusercontent.com/41600149/148709069-3090d73d-c3c3-4a93-8d26-56c02f9fb960.png)

3. Click Authenticate:
![image](https://user-images.githubusercontent.com/41600149/148709104-8d8835fb-91b3-4b49-8f1a-6b43fee3d8d8.png)
Console didn't change

4. Select Metamask - Nothing happens - But the console changes:
![image](https://user-images.githubusercontent.com/41600149/148709128-b13aac73-388f-41f3-b64d-7a9ed5965a89.png)
Let's click again:
![image](https://user-images.githubusercontent.com/41600149/148709136-dafc7763-f68d-408d-ad0d-81ff42ec4c4f.png)
Let's click other wallets now:
![image](https://user-images.githubusercontent.com/41600149/148709148-369ff85f-066c-4eb9-bf7a-509ca79cd1a8.png)
Reminds me, My friend tried to connect with WalletConnect and the connection said Connected but it never got the address and showed that he logged in
Let's actually click more working wallets now:
![image](https://user-images.githubusercontent.com/41600149/148709186-cbe62c0e-b6b2-48b6-b11c-1d76b713b331.png)
As you can see my problem seems to be comming from `Chains.jsx`, as indicated by line 91 of that file where the chain is being reported as null for some reason only when the browser is closed and reopened.
I assumed the problem comes from the localStorage but never actually was able to resolve it myself and so I will be super grateful for any help on that topic :)
-

Also changed BrowserRouter to HashBrowser allowing routes to be accessed when you refresh.. but the issue was there before it.

**Comment by orrburgel** [comment]
Solved it somehow forget how

**Comment by nguyenkien1402** [comment]
@burgil  hey mate, how did you solve this issue?
I'm having the same issue and much appreciate your help on this

**Comment by burgil** [comment]
Step 1. Never give up
Step 2. Never give up
Step 3. Thinking about step 4 while writing step 3
Step 4. Never stop trying

**Comment by burgil** [comment]
I think it was something with the localStorage, it got messed up somehow, you need to rewrite that logic

**Comment by nguyenkien1402** [comment]
After step 1, I switch to another browser like Edge and it works like normal. I guess it is something wrong with google chrome. Haven't reset Google Chrome yet to see any effect but I think it shouldn't be an issue since it can impact user experiences.
