### ISSUE TITLE
WalletConnect - Unable to Login and Laggy

### ISSUE THREAD

**Issue by beyondthecode-bc** [ethereum-boilerplate/ethereum-boilerplate#90]
Hello,

While using WalletConnect to connect an external wallet (from mobile MM or TW and from desktop Wallet3), I'm unable to login. The Wallet Address that is returned is NULL. Also, while scanning the QR Code, 7 out of 10 tries, it fails to connect.

Thanks

**Comment by andreachello** [comment]
I opened this issue a couple of weeks ago as well, unfortunately they closed it and said they would implement it in the future, however, most users use their mobile phones rather than their computers in order to view websites, so it is a major issue to be solved

**Comment by beyondthecode-bc** [comment]
https://forum.moralis.io/t/walletconnet-returns-null-address/7717/3 - based on what @Y0moo said, we will have the FIX soon :) hopefully...
