### ISSUE TITLE
missing hook "useNFTBalance"

### ISSUE THREAD

**Issue by MontyWilliams** [ethereum-boilerplate/ethereum-boilerplate#94]
in src/components/hooks useNFTBalances is like missing totally. its imprtted from react-Moralis so it works out the box but in the tutorial he modifies it. I think I can solve it but come on bruh what is this like a test or something? surely you know its missing.

**Comment by YosephKS** [comment]
Hey @MontyWilliams you can make a custom hook with the `useNFTBalances` and that shouldn't be a problem 🙌🏼 Also I think this will be concern more appropriate to the tutorial repo you're referring to instead of the Ethereum Boilerplate
